version: '3.8'

services:
  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    restart: unless-stopped
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml:ro
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'

  consul:
    image: consul:latest
    container_name: consul
    restart: unless-stopped
    ports:
      - "8500:8500"    # HTTP API and Web UI
      - "8600:8600/udp" # DNS
      - "8300:8300"    # Server RPC
      - "8301:8301"    # Serf LAN
      - "8302:8302"    # Serf WAN
    volumes:
      - ./consul/consul.hcl:/consul/config/consul.hcl:ro
      - consul-data:/consul/data
    command:
      - 'consul'
      - 'agent'
      - '-config-file=/consul/config/consul.hcl'

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost/grafana
    depends_on:
      - loki

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml:ro

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3030:3000"
    environment:
      - MB_DB_TYPE=${MB_DB_TYPE:-postgres}
      - MB_DB_CONNECTION_URI=${MB_DB_CONNECTION_URI}
      - MB_SITE_URL=${MB_SITE_URL:-http://localhost/metabase}
    volumes:
      - metabase-data:/metabase.db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - grafana
      - consul
      - blackbox-exporter

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    ports:
      - "9080:9080"
    volumes:
      - /var/log:/var/log:ro
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yaml:ro
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=200h'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.external-url=http://localhost/prometheus/'
      - '--web.route-prefix=/'

volumes:
  loki-data:
  metabase-data:
  prometheus-data:
  consul-data: