server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: push_api
    loki_push_api:
      server:
        http_listen_port: 1515
        log_level: "debug"
      labels:
        job: "dockerjson"
    pipeline_stages:
       - timestamp:
           source: timestamp
           format: RFC3339

  - job_name: s3_logs
    s3:
      bucket: ${S3_LOGS_BUCKET_NAME}          # Environment variable for bucket
      prefix: ${S3_LOGS_PREFIX}               # Environment variable for prefix
      poll_interval: 5s
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            message: msg
            level: level
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          job: "s3_logs"
          bucket: ${S3_LOGS_BUCKET_NAME}      # Reuse bucket name in labels
          level:
      - output:
          source: message