server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: push_api
    loki_push_api:
      server:
        http_listen_port: 1515
        log_level: "debug"
      labels:
        job: "dockerjson"
    pipeline_stages:
      - timestamp:
          source: timestamp
          format: RFC3339
